#!/bin/bash --

usage() {
	cat << EOF
usage: `basename $0` [option] pattern
  option:
    -a (default)       search all (apt-cache search)
    -n                 search not installed only (apt-cache search not in dpkg -l)
    -i                 search installed (dpkg -l)
    -s                 strict search: search pattern in package names only
EOF
}

searchtype='a'
acoptions=''
while getopts 'anis' o; do
	case "$o" in
		a) searchtype='a' ;;
		n) searchtype='ni' ;;
		i) searchtype='i' ;;
		s) acoptions=' --names-only' ;;
		?) usage; exit 1 ;;
	esac
done

if [ ! $OPTIND -eq $# ]; then usage; exit 1; fi

shift $(( $OPTIND-1 ))
search="$1"

installed="`dpkg -l | grep -o -P '(?<=^[a-z]i)\s+[^\s:]+(?=\s|:)'`"

while read l; do
	p=${l%% *}
	pd=${l#* }
	sp=" $( echo $p | sed 's:\([-.\:]*[0-9]\+\)\+:([-.\:]*[0-9]+)*:g' )([-.:]*[0-9]+)*\$"
	vs=$( echo "$installed" | grep -o -P "$sp" )
	i=$( echo "$vs" | grep " $p" )
	if [ -z "$i" -a "$searchtype" != "i" -o -n "$i" -a "$searchtype" != "ni" ]; then
		if [ -z "$i" ]; then
			color='\e[1;31m'
			also=''
		else
			color='\e[1;32m'
			also='also '
			vs=$( echo "$vs" | grep -v " $p" )
		fi
		[ -z "$vs" ] || vs=' ('$also'installed:\e[0;32m'${vs% }'\e[0m)'
		echo -e "$color$p\e[0m"$vs" $pd"
	fi
done < <( apt-cache search$acoptions "$search" | sort )
